doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        mapping_types:
          enum: string
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            MNGame:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Database/Entity'
                prefix: 'MNGame\Database\Entity'
                alias: MNGame
