nelmio_api_doc:
    documentation:
        info:
            title: GameSitesApi
            description: 'Dokumentacj aplikacji GameSites mająca na coelu udostępnienie funkcjonalności strony osobą,
             które chca wykorzystać własny fronto do integracji z naszą plikacją. Strona ta pozwala na zapoznanie się
             wpełni z działniem apliakcji od strony backendowej.'
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/documentation$)
        host_patterns:
            - ^api\.
