nelmio_api_doc:
  documentation:
    schemes: [http]
    info:
      title: ModernGame OpenAPI
      description: Api of a Moderngame server group
      version: 0.63.0
    securityDefinitions:
     authorization:
        type: apiKey
        name: X-AUTH-TOKEN
        in: Header
  areas:
    path_patterns:
      - ^/v1(?!/documentation)
