security:
    providers:
        ModernGame:
            entity:
                class: ModernGame\Database\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout: ~
            guard:
                authenticators:
                    - ModernGame\Security\TokenAuthenticator

    encoders:
        ModernGame\Database\Entity\User: bcrypt

    access_control:
        - { path: ^/v1/contact, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/shop, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/rules, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/article, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/player, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/documentation, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/user/items, roles: ROLE_USER, method: [POST, GET, PUT, DELETE] }
        - { path: ^/v1/user, roles: ROLE_USER, method: [POST, GET, PUT, DELETE] }
        - { path: ^/v1/user/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/admin/, roles: ROLE_ADMIN, method: [POST, GET, PUT, DELETE]}
        - { path: ^/v1/, roles: ROLE_USER, method: [POST, GET, PUT, DELETE] }
