security:
    providers:
        GemDust:
            entity:
                class: App\General\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: /user/login
                check_path: /user/login
            logout:
                path:   /user/logout
                target: /

    encoders:
        App\General\Entity\User: bcrypt

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/api/, roles: ROLE_ADMIN }
