# ---------- Article
admin-article-post:
  path:       /article
  controller: ModernGame\Controller\Admin\ArticleController::postArticle
  methods:    [POST]
admin-article-get:
  path:       /article
  controller: ModernGame\Controller\Admin\ArticleController::getEntity
  methods:    [GET]
admin-article-put:
  path:       /article
  controller: ModernGame\Controller\Admin\ArticleController::putArticle
  methods:    [PUT]
admin-article-delete:
  path:       /article
  controller: ModernGame\Controller\Admin\ArticleController::deleteEntity
  methods:    [DELETE]

# ---------- Contact
admin-contact-post:
  path:       /contact
  controller: ModernGame\Controller\Admin\ContactController::postTicket
  methods:    [POST]
admin-contact-get:
  path:       /contact
  controller: ModernGame\Controller\Admin\ContactController::getEntity
  methods:    [GET]
admin-contact-delete:
  path:       /contact
  controller: ModernGame\Controller\Admin\ContactController::deleteEntity
  methods:    [DELETE]

# ---------- Item
admin-item-post:
  path:       /item
  controller: ModernGame\Controller\Admin\ItemController::postItem
  methods:    [POST]
admin-item-get:
  path:       /item
  controller: ModernGame\Controller\Admin\ItemController::getEntity
  methods:    [GET]
admin-item-put:
  path:       /item
  controller: ModernGame\Controller\Admin\ItemController::putItem
  methods:    [PUT]
admin-item-delete:
  path:       /item
  controller: ModernGame\Controller\Admin\ItemController::deleteEntity
  methods:    [DELETE]

# ---------- ItemList
admin-item-list-post:
  path:       /item/list
  controller: ModernGame\Controller\Admin\ItemListController::postItemList
  methods:    [POST]
admin-item-list-get:
  path:       /item/list
  controller: ModernGame\Controller\Admin\ItemListController::getEntity
  methods:    [GET]
admin-item-list-put:
  path:       /item/list
  controller: ModernGame\Controller\Admin\ItemListController::putItemList
  methods:    [PUT]
admin-item-list-delete:
  path:       /item/list
  controller: ModernGame\Controller\Admin\ItemListController::deleteEntity
  methods:    [DELETE]

# ---------- Mod
admin-mod-post:
  path:       /mod
  controller: ModernGame\Controller\Admin\ModController::postMod
  methods:    [POST]
admin-mod-get:
  path:       /mod
  controller: ModernGame\Controller\Admin\ModController::getEntity
  methods:    [GET]
admin-mod-put:
  path:       /mod
  controller: ModernGame\Controller\Admin\ModController::putMod
  methods:    [PUT]
admin-mod-delete:
  path:       /mod
  controller: ModernGame\Controller\Admin\ModController::deleteEntity
  methods:    [DELETE]

# ---------- Regulation
admin-regulation-post:
  path:       /regulation
  controller: ModernGame\Controller\Admin\RegulationController::postRegulation
  methods:    [POST]
admin-regulation-get:
  path:       /regulation
  controller: ModernGame\Controller\Admin\RegulationController::getEntity
  methods:    [GET]
admin-regulation-put:
  path:       /regulation
  controller: ModernGame\Controller\Admin\RegulationController::putRegulation
  methods:    [PUT]
admin-regulation-delete:
  path:       /regulation
  controller: ModernGame\Controller\Admin\RegulationController::deleteEntity
  methods:    [DELETE]

# ---------- Regulation Category
admin-regulation-category-post:
  path:       /regulation/category
  controller: ModernGame\Controller\Admin\RegulationCategoryController::postRegulationCategory
  methods:    [POST]
admin-regulation-category-get:
  path:       /regulation/category
  controller: ModernGame\Controller\Admin\RegulationCategoryController::getEntity
  methods:    [GET]
admin-regulation-category-put:
  path:       /regulation/category
  controller: ModernGame\Controller\Admin\RegulationCategoryController::putRegulationCategory
  methods:    [PUT]
admin-regulation-category-delete:
  path:       /regulation/category
  controller: ModernGame\Controller\Admin\RegulationCategoryController::deleteEntity
  methods:    [DELETE]

# ---------- Statistic
admin-item-list-statistic-get:
  path:       /item/list/statistic
  controller: ModernGame\Controller\Admin\StatisticController::getItemListStatistic
  methods:    [GET]
admin-payment-history-get:
  path:       /payment/history
  controller: ModernGame\Controller\Admin\StatisticController::getPaymentHistory
  methods:    [GET]

# ---------- User
admin-user-get:
  path:       /user
  controller: ModernGame\Controller\Admin\UserController::getEntity
  methods:    [GET]
admin-user-put:
  path:       /user
  controller: ModernGame\Controller\Admin\UserController::putUser
  methods:    [PUT]
admin-user-delete:
  path:       /user
  controller: ModernGame\Controller\Admin\UserController::deleteEntity
  methods:    [DELETE]
