# ---------- Article
admin-article-post:
  path:       /article
  controller: ModernGame\Controller\Admin\ArticleController::postArticle
  methods:    [POST]
admin-article-put:
  path:       /article
  controller: ModernGame\Controller\Admin\ArticleController::putArticle
  methods:    [PUT]
admin-article-delete:
  path:       /article
  controller: ModernGame\Controller\Admin\ArticleController::deleteArticle
  methods:    [DELETE]
admin-article-get:
  path:       /article
  controller: ModernGame\Controller\Admin\ArticleController::getArticle
  methods:    [GET]

# ---------- ItemList
admin-item-list-post:
  path:       /item/list
  controller: ModernGame\Controller\Admin\ItemListController::postItemList
  methods:    [POST]
admin-item-list-put:
  path:       /item/list
  controller: ModernGame\Controller\Admin\ItemListController::putItemList
  methods:    [PUT]
admin-item-list-delete:
  path:       /item/list
  controller: ModernGame\Controller\Admin\ItemListController::deleteItemList
  methods:    [DELETE]
admin-item-list-get:
  path:       /item/list
  controller: ModernGame\Controller\Admin\ItemListController::getItemList
  methods:    [GET]

# ---------- Item
admin-item-post:
  path:       /item
  controller: ModernGame\Controller\Admin\ItemController::postItem
  methods:    [POST]
admin-item-put:
  path:       /item
  controller: ModernGame\Controller\Admin\ItemController::putItem
  methods:    [PUT]
admin-item-delete:
  path:       /item
  controller: ModernGame\Controller\Admin\ItemController::deleteItem
  methods:    [DELETE]
admin-item-get:
  path:       /item
  controller: ModernGame\Controller\Admin\ItemController::getItem
  methods:    [GET]

# ---------- Mod
admin-mod-post:
  path:       /mod
  controller: ModernGame\Controller\Admin\ModController::postMod
  methods:    [POST]
admin-mod-put:
  path:       /mod
  controller: ModernGame\Controller\Admin\ModController::putMod
  methods:    [PUT]
admin-mod-delete:
  path:       /mod
  controller: ModernGame\Controller\Admin\ModController::deleteMod
  methods:    [DELETE]
admin-mod-get:
  path:       /mod
  controller: ModernGame\Controller\Admin\ModController::getMod
  methods:    [DELETE]

# ---------- Regulation Category
admin-regulation-category-post:
  path:       /regulation/category
  controller: ModernGame\Controller\Admin\RegulationCategoryController::postRegulationCategory
  methods:    [POST]
admin-regulation-category-put:
  path:       /regulation/category
  controller: ModernGame\Controller\Admin\RegulationCategoryController::putRegulationCategory
  methods:    [PUT]
admin-regulation-category-delete:
  path:       /regulation/category
  controller: ModernGame\Controller\Admin\RegulationCategoryController::deleteRegulationCategory
  methods:    [DELETE]
admin-regulation-category-get:
  path:       /regulation/category
  controller: ModernGame\Controller\Admin\RegulationCategoryController::getRegulationCategory
  methods:    [GET]

# ---------- Regulation
admin-regulation-post:
  path:       /regulation
  controller: ModernGame\Controller\Admin\RegulationController::postRegulation
  methods:    [POST]
admin-regulation-put:
  path:       /regulation
  controller: ModernGame\Controller\Admin\RegulationController::putRegulation
  methods:    [PUT]
admin-regulation-delete:
  path:       /regulation
  controller: ModernGame\Controller\Admin\RegulationController::deleteRegulation
  methods:    [DELETE]
admin-regulation-get:
  path:       /regulation
  controller: ModernGame\Controller\Admin\RegulationController::getRegulation
  methods:    [GET]

# ---------- Contact
admin-contact-put:
  path:       /contact
  controller: ModernGame\Controller\Admin\ContactController::putTicket
  methods:    [PUT]
admin-contact-delete:
  path:       /contact
  controller: ModernGame\Controller\Admin\ContactController::deleteTicket
  methods:    [DELETE]
admin-contact-get:
  path:       /contact
  controller: ModernGame\Controller\Admin\ContactController::getTicket
  methods:    [GET]

# ---------- User
admin-user-put:
  path:       /user
  controller: ModernGame\Controller\Admin\UserController::putUser
  methods:    [PUT]
admin-user-delete:
  path:       /user
  controller: ModernGame\Controller\Admin\UserController::deleteUser
  methods:    [DELETE]
admin-user-get:
  path:       /user
  controller: ModernGame\Controller\Admin\UserController::getUserData
  methods:    [GET]
