# ---------- Article
admin-article-post:
  path:       /article
  controller: ModernGame\Controller\Admin\ArticleController::postArticle
  methods:    [POST]
admin-article-put:
  path:       /article
  controller: ModernGame\Controller\Admin\ArticleController::putArticle
  methods:    [PUT]
admin-article-delete:
  path:       /article
  controller: ModernGame\Controller\Admin\ArticleController::deleteArticle
  methods:    [DELETE]
# ---------- ItemList
admin-item-list-post:
  path:       /item/list
  controller: ModernGame\Controller\Admin\ItemListController::postItemList
  methods:    [POST]
admin-item-list-put:
  path:       /item/list
  controller: ModernGame\Controller\Admin\ItemListController::putItemList
  methods:    [PUT]
admin-item-list-delete:
  path:       /item/list
  controller: ModernGame\Controller\Admin\ItemListController::deleteItemList
  methods:    [DELETE]
