routes:
  resource: 'admin.yaml'
  prefix:   /admin

# ---------- USER
login:
  path:       /user/login
  controller: ModernGame\Controller\UserController::login
  methods:    [POST]
login-launcher:
  path:       /user/launcher/login
  controller: ModernGame\Controller\UserController::loginInLauncher
  methods:    [POST]
register:
  path:       /user/register
  controller: ModernGame\Controller\UserController::register
  methods:    [POST]
reset-password:
  path:       /user/reset
  controller: ModernGame\Controller\UserController::resetPassword
  methods:    [POST]
reset-from-token:
  path:       /user/reset/{token}
  controller: ModernGame\Controller\UserController::resetFromToken
  methods:    [POST]
user-update:
  path:       /user
  controller: ModernGame\Controller\UserController::update
  methods:    [PUT]
item-list:
  path:       /user/item/list
  controller: ModernGame\Controller\UserController::getItemList
  method:     [GET]

# ---------- Player
player-avatar:
  path:       /player/avatar
  controller: ModernGame\Controller\PlayerController::getPlayerAvatar
  methods:    [GET]
player-list:
  path:       /player/list
  controller: ModernGame\Controller\PlayerController::getPlayerList
  methods:    [GET]

# ---------- Payments
cash:
  path:       /cash
  controller: ModernGame\Controller\AfterLogin\WalletController::cash
  methods:    [GET]
pypal-confirmation:
  path:       /payment/paypal
  controller: ModernGame\Controller\AfterLogin\WalletController::paypalExecute
  methods:    [POST]
sms-confirmation:
  path:       /payment/sms
  controller: ModernGame\Controller\AfterLogin\WalletController::microSMSExecute
  methods:    [POST]

# ---------- ItemShop
get-items:
  path:       /shop/list
  controller: ModernGame\Controller\AfterLogin\ItemShopController::getItemList
  methods:    [GET]
buy-item:
  path:       /shop/buy
  controller: ModernGame\Controller\AfterLogin\ItemShopController::buyItemList
  methods:    [POST]
item-execute:
  path:       /shop/item
  controller: ModernGame\Controller\AfterLogin\ItemShopController::itemExecute
  methods:    [POST]
item-list-execute:
  path:       /shop/items
  controller: ModernGame\Controller\AfterLogin\ItemShopController::itemListExecute
  methods:    [POST]

# ---------- Contact
contact:
  path:       /contact
  controller: ModernGame\Controller\ContactController::setMessageContact
  methods:    [POST]
contact-ticket:
  path:       /contact/{ticket}
  controller: ModernGame\Controller\ContactController::getMessagesTicket
  methods:    [GET]

# ---------- Article
article:
  path:       /article
  controller: ModernGame\Controller\Content\ArticleController::getArticleList
  methods:    [GET]
