routes:
  resource: 'admin.yaml'
  prefix:   /admin

# ---------- Article
article:
  path:       /article
  controller: ModernGame\Controller\Content\ArticleController::getArticle
  methods:    [GET]

# ---------- Contact
contact:
  path:       /contact
  controller: ModernGame\Controller\ContactController::setMessageContact
  methods:    [POST]
contact-ticket:
  path:       /contact
  controller: ModernGame\Controller\ContactController::getMessagesTicket
  methods:    [GET]

# ---------- ItemShop
shop-buy-item:
  path:       /shop/buy
  controller: ModernGame\Controller\AfterLogin\ItemShopController::buyItemList
  methods:    [POST]
shop-paypal-execute-item-list:
  path:       /shop/execute/paypal
  controller: ModernGame\Controller\AfterLogin\ItemShopController::payPalExecute
  methods:    [POST]
shop-dotpay-execute-item-list:
  path:       /shop/execute/dotpay
  controller: ModernGame\Controller\AfterLogin\ItemShopController::dotPayExecute
  methods:    [POST]
shop-get-prices:
  path:       /shop/sms/prices
  controller: ModernGame\Controller\AfterLogin\ItemShopController::getSMSPrices
  methods:    [GET]
shop-get-items:
  path:       /shop/list
  controller: ModernGame\Controller\AfterLogin\ItemShopController::getItemList
  methods:    [GET]

# ---------- Player
player-avatar:
  path:       /player/avatar
  controller: ModernGame\Controller\PlayerController::getMinecraftAvatar
  methods:    [GET]
player-list:
  path:       /player/list
  controller: ModernGame\Controller\PlayerController::getPlayerList
  methods:    [GET]
player:
  path:       /player
  controller: ModernGame\Controller\PlayerController::getPlayer
  methods:    [GET]

# ---------- Prepaid
payment-paypal-confirmation:
  path:       /prepaid/paypal
  controller: ModernGame\Controller\AfterLogin\WalletController::paypalExecute
  methods:    [POST]
payment-dotpay-confirmation:
  path:       /prepaid/dotpay
  controller: ModernGame\Controller\AfterLogin\WalletController::dotPayExecute
  methods:    [POST]
payment-sms-confirmation:
  path:       /prepaid/sms
  controller: ModernGame\Controller\AfterLogin\WalletController::microSMSExecute
  methods:    [POST]
wallet-cash:
  path:       /prepaid/status
  controller: ModernGame\Controller\AfterLogin\WalletController::cash
  methods:    [GET]

# ---------- Regulation
rules:
  path:       /rules
  controller: ModernGame\Controller\Content\RegulationController::getRules
  methods:    [GET]

# ---------- User
user-login:
  path:       /user/login
  controller: ModernGame\Controller\UserController::login
  methods:    [POST]
user-login-launcher:
  path:       /user/launcher/login
  controller: ModernGame\Controller\UserController::loginMinecraft
  methods:    [POST]
user-register:
  path:       /user/register
  controller: ModernGame\Controller\UserController::register
  methods:    [POST]
user-reset-password:
  path:       /user/reset
  controller: ModernGame\Controller\UserController::resetPassword
  methods:    [POST]
user-item-execute:
  path:       /user/item
  controller: ModernGame\Controller\UserController::itemExecute
  methods:    [POST]
user-item-list-execute:
  path:       /user/item/list
  controller: ModernGame\Controller\UserController::itemListExecute
  methods:    [POST]
user-item-list:
  path:       /user/items
  controller: ModernGame\Controller\UserController::getItemList
  methods:    [GET]
user-data:
  path:       /user
  controller: ModernGame\Controller\UserController::getUserData
  methods:    [GET]
user-reset-from-token:
  path:       /user/password
  controller: ModernGame\Controller\UserController::resetFromToken
  methods:    [PUT]
user-update:
  path:       /user
  controller: ModernGame\Controller\UserController::update
  methods:    [PUT]
