# ---------- Article
additional-info:
  path:       /info
  controller: ModernGame\Controller\Backend\AdditionalInfoController::getPageAdditionalInfo
  methods:    [GET]

# ---------- Article
article:
  path:       /article
  controller: ModernGame\Controller\Backend\ArticleController::getArticle
  methods:    [GET]

# ---------- Contact
contact:
  path:       /contact
  controller: ModernGame\Controller\ContactController::setMessageContact
  methods:    [POST]
contact-ticket:
  path:       /contact
  controller: ModernGame\Controller\ContactController::getMessagesTicket
  methods:    [GET]
logged-contact-ticket:
  path:       /contact/list
  controller: ModernGame\Controller\ContactController::getMyTickets
  methods:    [GET]

# ---------- ItemShop
shop-buy-item:
  path:       /shop/buy
  controller: ModernGame\Controller\Backend\ItemShopController::buyItemList
  methods:    [POST]
shop-paypal-execute-item-list:
  path:       /shop/execute/paypal
  controller: ModernGame\Controller\Backend\ItemShopController::payPalExecute
  methods:    [POST]
shop-sms-execute-item-list:
  path:       /shop/execute/sms
  controller: ModernGame\Controller\Backend\ItemShopController::microSMSExecute
  methods:    [POST]
shop-get-prices:
  path:       /shop/sms/prices
  controller: ModernGame\Controller\Backend\ItemShopController::getSMSPrices
  methods:    [GET]
shop-get-items:
  path:       /shop/list
  controller: ModernGame\Controller\Backend\ItemShopController::getItemList
  methods:    [GET]

# ---------- Player
player-avatar:
  path:       /player/avatar
  controller: ModernGame\Controller\Backend\PlayerController::getMinecraftAvatar
  methods:    [GET]
player-list:
  path:       /player/list
  controller: ModernGame\Controller\Backend\PlayerController::getPlayerList
  methods:    [GET]
player:
  path:       /player
  controller: ModernGame\Controller\Backend\PlayerController::getPlayer
  methods:    [GET]

# ---------- Prepaid
payment-paypal-confirmation:
  path:       /prepaid/paypal
  controller: ModernGame\Controller\Backend\PrepaidController::paypalExecute
  methods:    [POST]
payment-sms-confirmation:
  path:       /prepaid/sms
  controller: ModernGame\Controller\Backend\PrepaidController::microSMSExecute
  methods:    [POST]
wallet-cash:
  path:       /prepaid/status
  controller: ModernGame\Controller\Backend\PrepaidController::cash
  methods:    [GET]

# ---------- Regulation
rules:
  path:       /rules
  controller: ModernGame\Controller\Backend\RegulationController::getRules
  methods:    [GET]

# ---------- User
user-login-launcher:
  path:       /user/launcher/login
  controller: ModernGame\Controller\Backend\UserController::loginMinecraft
  methods:    [POST]
user-validate-launcher:
  path:       /user/launcher/validate
  controller: ModernGame\Controller\Backend\UserController::validateMinecraft
  methods:    [POST]
user-invalidate-launcher:
  path:       /user/launcher/validate
  controller: ModernGame\Controller\Backend\UserController::invalidateMinecraft
  methods:    [POST]
user-refresh-launcher:
  path:       /user/launcher/refresh
  controller: ModernGame\Controller\Backend\UserController::refreshMinecraft
  methods:    [POST]
user-reset-password:
  path:       /user/reset
  controller: ModernGame\Controller\Backend\UserController::resetPassword
  methods:    [POST]
user-item-execute:
  path:       /user/item
  controller: ModernGame\Controller\Backend\UserController::itemExecute
  methods:    [POST]
user-item-list-execute:
  path:       /user/item/list
  controller: ModernGame\Controller\Backend\UserController::itemListExecute
  methods:    [POST]
user-item-list:
  path:       /user/items
  controller: ModernGame\Controller\Backend\UserController::getItemList
  methods:    [GET]
user-data:
  path:       /user
  controller: ModernGame\Controller\Backend\UserController::getUserData
  methods:    [GET]
user-reset-from-token:
  path:       /user/password
  controller: ModernGame\Controller\Backend\UserController::resetFromToken
  methods:    [PUT]
user-update:
  path:       /user
  controller: ModernGame\Controller\Backend\UserController::update
  methods:    [PUT]
