parameters:
  locale: 'pl'
  google:
    recaptcha: '6LfwhcQZAAAAAJBPmY2tgGvITdZbSSt692Zn9tHb'
    siteKey: '6LfwhcQZAAAAALY5FSmCcRdfDCE7quCozrzEyQIE'
  whitelistCommands: [ unban, pardon, ban ]
  defaultQueryServerId: 1
  defaultConnectionServerId: 1
  old: 'base'
  latest: 'new'

  server:
    1:
      id: 1
      name: 'MGame'
      host: '127.0.0.1'
      queryPort: '21370'
      port: '12345'
      password: '7d9aaEfbb73A'
      paypal:
        client: 'AcshzYPPq0YGpv0Trz5aysOQ-hx0jxNzMbjHZrSYYw6teXfAaScSde4XGaTuc5d3XTwJEtDqEozwRbFC'
#                client: 'Aaskn_HyRuesP0qQRmzFWFKat8o8UC4pHgzmdEUZUUiFTGjUIbuycQcZAFniOjtK_e9QETDDleCl-Cwv'
        secret: 'ENW0ij8yxYsbDWyEvwK4SZ3SR08V6eeP0tMYZLsoVAwYDxnP0xq-RKpKL3St3SoKsoQYi-V4AO63U9-5'
#                secret: 'EBn_slN84rAb8fNQIqsPz5H_Rk8v4Ua5SV27sjTodts5L0RB5ZHkO84hMCSO-Z1NwJpBEqMgMGgBq1QG'
      microSMS:
        userId: 2003
        serviceId: 3235
      defaultCommand: 'list'
      playerNotFoundCommunicate: 'Player not found.'
      src: 'assets/logotype.jpg'
      additionalCards:
        Download: 'launcher'
      executionType: 'ws'
    2:
      id: 2
      name: 'GuildWar'
      host: '95.214.52.188'
      port: '25576'
      password: 'uZrBMBbzfP'
      paypal:
        client: 'AcshzYPPq0YGpv0Trz5aysOQ-hx0jxNzMbjHZrSYYw6teXfAaScSde4XGaTuc5d3XTwJEtDqEozwRbFC'
        secret: 'ENW0ij8yxYsbDWyEvwK4SZ3SR08V6eeP0tMYZLsoVAwYDxnP0xq-RKpKL3St3SoKsoQYi-V4AO63U9-5'
      microSMS:
        userId: 2003
        serviceId: 3235
      defaultCommand: 'list'
      playerNotFoundCommunicate: 'Player not found.'
      src: 'assets/guildwar_logo.png'
      executionType: 'ws'