parameters:
    locale: 'pl'
    microSMS:
        userId: 2003
        serviceId: 3235
    paypal:
        client: 'Aaskn_HyRuesP0qQRmzFWFKat8o8UC4pHgzmdEUZUUiFTGjUIbuycQcZAFniOjtK_e9QETDDleCl-Cwv'
        secret: 'EBn_slN84rAb8fNQIqsPz5H_Rk8v4Ua5SV27sjTodts5L0RB5ZHkO84hMCSO-Z1NwJpBEqMgMGgBq1QG'
    recaptcha: '6LdGKMUUAAAAAAAcXOywQS6SwBQx25nUApvXz-3z'
    minecraft:
        host: '83.25.13.28'
        port: '25575'
        password: 'qwerty'
    command:
        list: 'list'
    multiplier: 1
    additionalInfo:
        serviceCost: 250

services:
    _defaults:
        autowire: true
        autoconfigure: true

    ModernGame\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    ModernGame\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    ModernGame\EventListener\ExceptionListener:
        arguments: ['@logger', '@ModernGame\Service\Mail\MailSenderService']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    ModernGame\Service\EnvironmentService:
        arguments: ['%kernel.environment%']

    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }
