imports:
  - { resource: 'parameters.yml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  ModernGame\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  ModernGame\EventListener\ExceptionListener:
    arguments: ['@logger', '@ModernGame\Service\Mail\MailSenderService']
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  ModernGame\Service\Connection\Minecraft\MojangPlayerService:
    autowire: true

  mojang.player.service:
    class: ModernGame\Service\Connection\Minecraft\MojangPlayerService

  ModernGame\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  ModernGame\Service\EnvironmentService:
    arguments: ['%kernel.environment%']

  get_set_method_normalizer:
    class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
    tags:
      - { name: serializer.normalizer }
