parameters:
    locale: 'pl'
    microSMS:
        userId: 2003
        serviceId: 3235
    paypal:
        client: 'AcshzYPPq0YGpv0Trz5aysOQ-hx0jxNzMbjHZrSYYw6teXfAaScSde4XGaTuc5d3XTwJEtDqEozwRbFC'
        secret: 'EKphnn0pTtiyegluAPXfuuk4pQW9dBB4SVLnF0a85LKpWhSyogY49b32gFxYvpC4Qdto9uIZrYFA0tpO'
    google:
      recaptcha: '6LfwhcQZAAAAAJBPmY2tgGvITdZbSSt692Zn9tHb'
      siteKey: '6LfwhcQZAAAAALY5FSmCcRdfDCE7quCozrzEyQIE'
    minecraft:
      1:
        host: 's719954.csrv.pl'
        port: '9728'
        password: 'f0286775a33ae71f1ef7'
    command:
        list: 'list'
    multiplier: 1
    additionalInfo:
        serviceCost: 250

services:
    _defaults:
        autowire: true
        autoconfigure: true

    ModernGame\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    ModernGame\Service\Connection\Minecraft\MojangPlayerService:
        autowire: true

    mojang.player.service:
      class: ModernGame\Service\Connection\Minecraft\MojangPlayerService

    ModernGame\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    ModernGame\EventListener\ExceptionListener:
        arguments: ['@logger', '@ModernGame\Service\Mail\MailSenderService']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    ModernGame\Service\EnvironmentService:
        arguments: ['%kernel.environment%']

    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }
