parameters:
    locale: 'pl'
    microSMS:
        userId: 2003
        serviceId: 3235
    paypal:
        client: 'AcshzYPPq0YGpv0Trz5aysOQ-hx0jxNzMbjHZrSYYw6teXfAaScSde4XGaTuc5d3XTwJEtDqEozwRbFC'
        secret: 'EKphnn0pTtiyegluAPXfuuk4pQW9dBB4SVLnF0a85LKpWhSyogY49b32gFxYvpC4Qdto9uIZrYFA0tpO'
    recaptcha: '6LdGKMUUAAAAAAAcXOywQS6SwBQx25nUApvXz-3z'
    minecraft:
        host: '83.25.13.28'
        port: '25575'
        password: 'qwerty'
    command:
        list: 'list'
    multiplier: 1
    dotPay:
        username: 'moderngameservice@gmail.com'
        password: '7d9aaefbb73a'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    ModernGame\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    ModernGame\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    ModernGame\EventListener\ExceptionListener:
        arguments: ['@logger', '@ModernGame\Service\Mail\MailSenderService']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    ModernGame\Service\EnvironmentService:
        arguments: ['%kernel.environment%']
